local function AddParticles()
	game.AddParticles("particles/weapon_hgun.pcf") -- idk why its dont work
	game.AddParticles("particles/weapon_tau.pcf")
	game.AddParticles("particles/weapon_egon.pcf")
	game.AddParticles("particles/weapon_hgun.pcf")
	game.AddParticles("particles/weapon_rpg.pcf")
	game.AddParticles("particles/weapon_magnum.pcf")
	game.AddParticles("particles/weapon_glock.pcf")
	game.AddParticles("particles/weapon_mp5.pcf")
	game.AddParticles("particles/weapon_shotgun.pcf")
	game.AddParticles("particles/weapon_tracer.pcf")
	game.AddParticles("particles/grenade_rpg.pcf")

	PrecacheParticleSystem("weapon_rpg_muzzleflash")
	PrecacheParticleSystem("world_weapon_rpg_muzzleflash")

	PrecacheParticleSystem("grenade_rpg_fire2")
	PrecacheParticleSystem("grenade_rpg_rope_trail")
	PrecacheParticleSystem("grenade_rpg_trail")
	PrecacheParticleSystem("grenade_rpg_trail_fire")
	PrecacheParticleSystem("grenade_rpg_trail_inner2")

	PrecacheParticleSystem("muzle_smoke_2_357")
	PrecacheParticleSystem("muzzle_core_357")
	PrecacheParticleSystem("muzzle_glow_357")
	PrecacheParticleSystem("muzzle_smoke_357")
	PrecacheParticleSystem("weapon_257_muzzle_flash")
	PrecacheParticleSystem("weapon_357_muzzle_spark")
	PrecacheParticleSystem("weapon_357_muzzle_trail")
	PrecacheParticleSystem("weapon_357_muzzleflash")
	PrecacheParticleSystem("wispy_smoke")
	PrecacheParticleSystem("wispy_smoke_orig")
	PrecacheParticleSystem("world_muzzle_357_trail")
	PrecacheParticleSystem("world_muzzle_core_357")
	PrecacheParticleSystem("world_muzzle_glow_357")
	PrecacheParticleSystem("world_muzzle_smoke_357")
	PrecacheParticleSystem("world_weapon_357_muzzleflash")
	PrecacheParticleSystem("world_weapon_357_spark")

	PrecacheParticleSystem("weapon_glock_muzzle")
	PrecacheParticleSystem("weapon_glock_muzzle_glow")
	PrecacheParticleSystem("weapon_glock_muzzle_smoke")
	PrecacheParticleSystem("weapon_glock_muzzleflash")
	PrecacheParticleSystem("weapon_glock_smoke")
	PrecacheParticleSystem("weapon_glock_sparks")
	PrecacheParticleSystem("world_weapon_glock")
	PrecacheParticleSystem("world_weapon_glock_muzzle_glow")
	PrecacheParticleSystem("world_weapon_glock_muzzleflash")
	PrecacheParticleSystem("world_weapon_glock_smoke")
	PrecacheParticleSystem("world_weapon_glock_sparks")

	PrecacheParticleSystem("muzzle_glow_large")
	PrecacheParticleSystem("muzzle_glow_mp5")
	PrecacheParticleSystem("muzzle_inner")
	PrecacheParticleSystem("muzzle_side")
	PrecacheParticleSystem("muzzle_side_glow")
	PrecacheParticleSystem("muzzle_smoke_mp5")
	PrecacheParticleSystem("muzzle_smoke_mp5_dark")
	PrecacheParticleSystem("muzzle_smoke_mp5_flash")
	PrecacheParticleSystem("muzzle_sparks_mp5")
	PrecacheParticleSystem("muzzle_top")
	PrecacheParticleSystem("muzzle_top_glow")
	PrecacheParticleSystem("muzzle_top_left_glow")
	PrecacheParticleSystem("weapon_357_muzzle_spark")
	PrecacheParticleSystem("weapon_mp5_muzzleflash")
	PrecacheParticleSystem("world_muzzle_core_mp5")
	PrecacheParticleSystem("world_muzzle_glow_mp5")
	PrecacheParticleSystem("world_muzzle_smoke_mp5")
	PrecacheParticleSystem("world_muzzle_sparks_mp5")
	PrecacheParticleSystem("world_weapon_mp5_muzzleflash")

	PrecacheParticleSystem("weapon_tracer")--maybe
	PrecacheParticleSystem("weapon_tracer_50cal")
	PrecacheParticleSystem("weapon_tracer_small")

	PrecacheParticleSystem("muzzle_bits_shotgun")
	PrecacheParticleSystem("muzzle_core_shotgun")
	PrecacheParticleSystem("muzzle_glow_shotgun")
	PrecacheParticleSystem("muzzle_inner_shotgun")
	PrecacheParticleSystem("muzzle_smoke_shotgun")
	PrecacheParticleSystem("muzzle_smoke_shotgun_flash")
	PrecacheParticleSystem("muzzle_sparks")
	PrecacheParticleSystem("muzzle_sparks_fly")
	PrecacheParticleSystem("muzzle_sparks_shotgun")
	PrecacheParticleSystem("muzzle_sparks_shotgun2")
	PrecacheParticleSystem("muzzle_sparks_shotgun3")
	PrecacheParticleSystem("weapon_shotgun_muzzleflash")
	PrecacheParticleSystem("world_muzzle_bits_shotgun")
	PrecacheParticleSystem("world_muzzle_core_shotgun")
	PrecacheParticleSystem("world_muzzle_glow_shotgun")
	PrecacheParticleSystem("world_muzzle_smoke_shotgun")
	PrecacheParticleSystem("world_muzzle_sparks_shotgun")
	PrecacheParticleSystem("world_weapon_shotgun_muzzleflash")

	PrecacheParticleSystem("weapon_hgun_vent_rope")
	PrecacheParticleSystem("weapon_hgun_muzzle_sprut")
	PrecacheParticleSystem("weapon_hgun_muzzle_sprut_3d")
	PrecacheParticleSystem("weapon_hgun_muzzleflash")
	PrecacheParticleSystem("weapon_hgun_muzzleflash_3rd")
	PrecacheParticleSystem("weapon_hgun_muzzleflash_light_1")
	PrecacheParticleSystem("weapon_hgun_muzzleflash_light_3d")
	PrecacheParticleSystem("weapon_hgun_smoke")
	PrecacheParticleSystem("weapon_hgun_smoke_3rd")
	PrecacheParticleSystem("weapon_hgun_vent_fire")
	PrecacheParticleSystem("weapon_hgun_vent_light")
	PrecacheParticleSystem("weapon_hgun_vent_spark")

	game.AddParticles("particles/hl2mmod_explosions.pcf")
	game.AddParticles("particles/hl2mmod_muzzleflashes.pcf")
	game.AddParticles("particles/hl2mmod_tracers.pcf")
	game.AddParticles("particles/hl2mmod_weaponeffects.pcf")

	PrecacheParticleSystem("hl2mmod_explosion_grenade")
	PrecacheParticleSystem("hl2mmod_explosion_rpg")
	PrecacheParticleSystem("hl2mmod_explosion_grenade_noaftersmoke")

end
pcall(AddParticles)

local function AddCustomAmmo()
	game.AddAmmoType({
		name = "Regenerating-AR3",
		maxcarry = 100
	})
end

timer.Simple(1, function()
	pcall(AddCustomAmmo) -- make sure they added
end)